# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstKraus_fun <- function(Y, mean_vec, cov_mat, index, alpha) {
    .Call(`_wfda_reconstKraus_fun`, Y, mean_vec, cov_mat, index, alpha)
}

