# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigenValues <- function(M) {
    .Call(`_wfda_getEigenValues`, M)
}

try_list <- function(r) {
    .Call(`_wfda_try_list`, r)
}

test_fda <- function(xxfdjk, betabasisj, betabasisk, range) {
    .Call(`_wfda_test_fda`, xxfdjk, betabasisj, betabasisk, range)
}

sum_cpp <- function(vec1) {
    .Call(`_wfda_sum_cpp`, vec1)
}

