# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstKraus_fun <- function(Y, mean_vec, cov_mat, index, alpha) {
    .Call(`_wfda_reconstKraus_fun`, Y, mean_vec, cov_mat, index, alpha)
}

eigenvalues <- function(V) {
    .Call(`_wfda_eigenvalues`, V)
}

inprod_cpp <- function(fd1, fd2, range, w) {
    .Call(`_wfda_inprod_cpp`, fd1, fd2, range, w)
}

vec <- function(G0, row_vec, col_vec, weights) {
    .Call(`_wfda_vec`, G0, row_vec, col_vec, weights)
}

compute <- function(f, Y, d_vec) {
    .Call(`_wfda_compute`, f, Y, d_vec)
}

check <- function(Y_first, d) {
    .Call(`_wfda_check`, Y_first, d)
}

